### ISSUE TITLE
Hardware developer docs page is empty

### ISSUE THREAD

**Issue by SkySpnc** [Project-Babble/BabbleDocs#34]
The [hardware page](https://docs.babble.diy/docs/developers/developerHE/developersHE) is empty. Perhaps mentioning that Babble now has a storage page for this may fit?

**Comment by dfgHiatus** [comment]
I propose that we redirect to the existing hardware pages - Or remove this outright and reword the software section accordingly.

**Comment by SkySpnc** [comment]
May also be worth removing the ref to the dev docs [here](https://docs.babble.diy/docs/software)
