### ISSUE TITLE
Step 2 of software setup is out of order

### ISSUE THREAD

**Issue by SkySpnc** [Project-Babble/BabbleDocs#35]
Step 2 of the [software setup page](https://docs.babble.diy/docs/software) advises that the serial/webcam ID setup guide is to come later in the docs, however the hardware page is stepped before this page is shown.

It may also be worth advising users to use [USBTreeView from uwe-sieber.de](https://www.uwe-sieber.de/usbtreeview_e.html) to assist in locating the correct device to enter into the Babble software.
Freshly enunerated devices show with a green highlight, and unplugged with a red highlight, a small but simple thing that can help when a user has many USB devices.

**Comment by dfgHiatus** [comment]
I think instead of saying:

> What exactly you need to put is explained in the hardware page.

We could instead say something along the lines of 

> You can use [USBTreeView](https://www.uwe-sieber.de/usbtreeview_e.html) to help find the camera address to input.

Seeking feedback on this proposition.
