### ISSUE TITLE
OV2640 120deg AliExpress URL leads to .us TLD

### ISSUE THREAD

**Issue by SkySpnc** [Project-Babble/BabbleDocs#36]
The Ali Express URL for the camera 2 (OV2640 120deg) on the [cameras page](https://docs.babble.diy/docs/hardware/components/Cameras) leads to aliexpress.us, which is not accessible in some regions. Alternatively it should direct to aliexpress.com.
The new URL would be https://www.aliexpress.com/item/3256804729833235.html

**Comment by dfgHiatus** [comment]
Good catch! I'll update this

**Comment by SkySpnc** [comment]
Also spotted the Freenove ESP32 link leads to aliexpress.us rather than .com on the [ESP32 page](https://docs.babble.diy/docs/hardware/components/ESP32s)
